Choco-Express/Choco-Express-FE

.github/workflows/deploy.yaml
src/App.jsx

✅ Test: CI/CD 테스트를 진행

---

.github/workflows/deploy.yaml
src/App.jsx

프론트엔드 리포지토리 CI/CD를 구축했습니다.
- #8

✨ Feature: CI/CD 구축

---

src/pages/CompletePage/CompletePage.jsx
src/pages/LetterPage/LetterPostPage.jsx

✨ Feature: 버튼 클릭 시 페이지 연결

---

src/pages/otherboxPage/otherboxPage.jsx
src/pages/otherboxPage/styled.js

🎨 Design: 상대방박스 조회 초콜릿 추가

---

src/components/ChocoSelector/styled.js
src/pages/LoginPage/LoginPage.jsx
src/pages/LoginPage/Styled.jsx
src/pages/MyboxSelectPage/MyboxSelectPage.jsx
src/pages/MyboxSelectPage/Styled.jsx

박스 셀렉터 선택 되었을 때 스타일을 바꾸었습니다.
mybox에서 문구도 잘 못 적어놔서 바꾸었어요.
- ex) #3

Design: 디자인 수정 및 API 초기 연결

---

package-lock.json
package.json
src/apis/instance.js
src/apis/otherBox.js
src/apis/postChoco.js
src/assets/images/Chocolates/Chocolate_5.svg
src/assets/images/Chocolates/Chocolate_6.svg
src/components/ChocoSelector/styled.js
src/components/common/Button/styled.js
src/constants/Chocolates/data.js
src/hooks/useOtherBox.js
src/pages/LetterPage/LetterPostPage.jsx
src/pages/otherboxPage/otherboxPage.jsx
src/router.jsx

✨ Feature: 상대방 박스 조회 API 연결

---

src/pages/LoginPage/LoginPage.jsx

Test: API 연결시도

---

src/hooks/useOtherBox.js
src/pages/CompletePage/CompletePage.jsx
src/pages/LetterPage/LetterPostPage.jsx
src/pages/otherboxPage/otherboxPage.jsx
src/router.jsx

> 라우터 주소 변경 및  API연결 확인했습니다.
- #22

✨ Feature: complete페이지 라우터 주소 변경

---

src/pages/CompletePage/CompletePage.jsx
src/pages/LetterPage/LetterPostPage.jsx
src/pages/otherboxPage/otherboxPage.jsx

< otherpostPage와 complete 간 데이터 전달 location 처리로 구성해봤습니다..!
- #22

✨ Feature: 페이지간 data 전달 location 처리

---

src/components/ChocoCheck/ChocoCheck22.jsx
src/components/ChocoCheck/ChocoCheck33.jsx
src/components/ChocoCheck/ChocoChoco22.js
src/components/ChocoCheck/styled.js
src/pages/ChocoList/ChocoList.jsx
src/pages/ChocoList/styled.js
src/pages/DetailLetter/DetailLetter.jsx

✅ Test: API 연결 시도 코드 테스트 

---

src/apis/instance.js
src/pages/CompletePage/styled.js

>타임아웃되었을 시 , 커스텀 오류 메세지 받았을 시,  status가 404 일 때 에러페이지로 다이렉트 되도록 구현했습니다.
- #22

✨ Feature: 에러페이지 연결

---

src/router.jsx

>오류페이지 리다이렉트 오류 수정 및 라우터 주소 수정했습니다.
- #22

🔥 Fix: 오류페이지 리다이렉트 오류 수정

---

src/apis/instance.js

🔥 Fix: 에러페이지 연동 오류 수정

---

src/pages/ChocoList/ChocoList.jsx

✅ api 코드 수정

---

src/components/NameSetting/NameSetting.jsx
src/components/common/Button/NextBtn.jsx
src/components/common/Heartbackground/styled.js
src/pages/MyboxPage/Styled.jsx
src/pages/MyboxSelectPage/MyboxSelectPage.jsx
src/pages/MyboxSelectPage/Styled.jsx

BoxSelector 마지막 다음으로 뜨는 부분을 완료로 수정하였습니다.
NameSetting의 기존 세팅을 기본값으로 두고 유동적으로 사용할 수 있도록 수정했어요
#14

🎨 Design: BoxSelector 다음 -> 완료 수정했습니다.

---

src/components/ChocoCheck/ChocoCheck22.jsx
src/components/ChocoCheck/ChocoCheck33.jsx
src/hooks/useOtherBox.js
src/pages/ChocoList/ChocoList.jsx
src/pages/ChocoList/styled.js
src/pages/DetailLetter/DetailLetter.jsx

✅ : 이미지 관리 코드 수정 Feature/#4

---

.env
.github/workflows/deploy.yaml
index.html
package-lock.json
package.json
src/hooks/useShare.js
src/pages/MyPage/MyPage.jsx
src/pages/MyPage/style.js
src/utils/shareInsta.js
src/utils/shareKakao.js

카카오톡 및 인스타그램 공유 기능을 구현했습니다.
- #65

[Feature] #65 - 카카오톡 및 인스타그램 공유 기능 구현

---

src/apis/instance.js
src/apis/otherBox.js

> 상대방 박스조회  API 요청 오류 수정
- #22

Fix: 상대방 박스조회  API 요청 오류 수정

---

src/apis/otherBox.js
src/hooks/useOtherBox.js
src/pages/otherboxPage/otherboxPage.jsx

> 상대방 박스 조회 페이지에서 토큰 유무에 따라 헤더 삭제여부 고려했습니다.
- #22

Fix: 상대방 박스 조회: 토큰 없을 시 헤더 지움

---

src/pages/otherboxPage/otherboxPage.jsx

>로그인페이지로 넘어가는 navigate 경로 설정 에러 수정했습니다.
- #22

Fix: navigate 경로 설정에러 수정

---

src/pages/otherboxPage/otherboxPage.jsx

>setting Storage에 담는 키 redirectURL->redurectUrl로 변경
- #22

Fix: redirectURL->redurectUrl로 변경

---

src/pages/DetailLetter/DetailLetter.jsx

✅ detailletter 초코 삭제 기능 및 부분 코드 수정

---

src/pages/ChocoList/ChocoList.jsx
src/pages/DetailLetter/DetailLetter.jsx

✅ otherData 콘솔 확인 및 병합 충돌

---

src/pages/DetailLetter/DetailLetter.jsx

Fix: 삭제 API요청 수정

---

package-lock.json
src/pages/CompletePage/styled.js
src/pages/LetterPage/styled.js
src/pages/LoginPage/Styled.jsx
src/pages/MyboxPage/Styled.jsx
src/pages/MyboxSelectPage/Styled.jsx
src/pages/NotFound/styled.js
src/pages/otherboxPage/styled.js

Fix: 미디어쿼리 설정
